version: '3'

services:
  ai-travel-planner:
    build: .
    ports:
      - "8000:8000"  # FastAPI backend
      - "8501:8501"  # Streamlit frontend
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SERPAPI_KEY=${SERPAPI_KEY}
    volumes:
      - ./:/app
    restart: unless-stopped